### ISSUE TITLE
Design and Interface

### ISSUE THREAD

**Issue by TalosTheGrea** [TalosTheGrea/Brown-Doodle-Company#1]
Create a template for slides

**Comment by TalosTheGrea** [comment]
Design a basic template first

**Comment by angelinechong** [comment]
Basic Template
Brown, Wood, Cardboard design style
*include screenshot of blank template

**Comment by angelinechong** [comment]
Basic Template
Brown, Wood, Cardboard design style
![image](https://user-images.githubusercontent.com/117239721/200233123-39f5c56d-b8e9-46b9-b275-ff9e6d5c9d61.png)

**Comment by TalosTheGrea** [comment]
Design looks good, move on to expanding the template with other types

**Comment by angelinechong** [comment]
Expanded Template
Logo and text font
Choice screen
Alternative choice screen

[png2jpg.zip](https://github.com/TalosTheGrea/Brown-Doodle-Company/files/9948652/png2jpg.zip)

**Comment by TalosTheGrea** [comment]
Design looks well done. Now, you can create template for transtion/loading screens

**Comment by angelinechong** [comment]
Transition Screen

[png2jpg (1).zip](https://github.com/TalosTheGrea/Brown-Doodle-Company/files/9948757/png2jpg.1.zip)

**Comment by TalosTheGrea** [comment]
Next, you can insert texts and details into templates based on finalized details from Design and Interface

**Comment by jia21001052** [comment]
ATM user interface

Design in the link below:
[https://www.canva.com/design/DAFRIweiSQ4/owRZzrzXIabd8CcZt-I4fQ/edit?utm_content=DAFRIweiSQ4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)

**Comment by TalosTheGrea** [comment]
All details seem to be included and organized into the template. All tasks have been completed for now, please wait for final checking and possible adjustments
