### ISSUE TITLE
ATM Menus & Functions

### ISSUE THREAD

**Issue by TalosTheGrea** [TalosTheGrea/Brown-Doodle-Company#2]
Decide on functions in ATM and appearing menus

**Comment by TalosTheGrea** [comment]
Start planning functions to-be included in the ATM

**Comment by NvTly** [comment]
Functions:
·Cash Withdrawal
·Balance Inquiry
·Instant Transfer
·PIN Change

Sub-Functions:
·Language selection (English, Malay, Chinese)

**Comment by TalosTheGrea** [comment]
All functions seem viable, can start planning on details of functions

**Comment by TalosTheGrea** [comment]
All functions seem viable, can start planning on details of functions

**Comment by NvTly** [comment]
Cash Withdrawal 
-Select from account
-Select amount
-Pin authentication

Balance Inquiry 
-Select from account
-Display amount

**Comment by NvTly** [comment]
Instant Transfer 
-Recipient bank
-Recipient bank acc number
-Enter PIN Number

PIN Change
-Enter current PIN number 
-Enter new PIN number
-Enter IC number (User authentication)

**Comment by TalosTheGrea** [comment]
Start planning functions to-be included in the ATM

**Comment by TalosTheGrea** [comment]
Details makes sense, add in details for transitions

**Comment by HengYpinn** [comment]
# The ATM will request for the card to be inserted and go into loading screen
# Any selection from main menu screen will go into loading screen
# The processing of any transaction after authentication will go into loading screen

Cash Withdrawal 
-Select from account
-Select amount
-Pin authentication

Balance Inquiry 
-Select from account
-Display amount

Instant Transfer 
-Recipient bank
-Recipient bank acc number
-Enter PIN Number (User authentication)

PIN Change
-Enter current PIN number 
-Enter new PIN number
-Enter IC number (User authentication)

**Comment by TalosTheGrea** [comment]
All details seem to be logical and realistic. All tasks have been completed for now, please wait for final checking and possible adjustments.
