### ISSUE TITLE
Finalization and Checking

### ISSUE THREAD

**Issue by TalosTheGrea** [TalosTheGrea/Brown-Doodle-Company#3]
Look through existing user interfaces to check if any additional details are required

Current adjustments required:
-Welcome Screen
-Thank you Screen
-Include "return to main menu" buttons in the transaction

**Comment by angelinechong** [comment]
Welcome and Thank you Screen

[png2jpg (2).zip](https://github.com/TalosTheGrea/Brown-Doodle-Company/files/9948951/png2jpg.2.zip)

**Comment by HengYpinn** [comment]
- ATM will always start in welcome screen
- The ATM will request for the card to be inserted and go into loading screen
- Any selection from main menu screen will go into loading screen
- The processing of any transaction after authentication will go into loading screen

Cash Withdrawal 
-Select from account (Return to Main Menu)
-Select amount
-Pin authentication

Balance Inquiry 
-Select from account (Return to Main Menu)
-Display amount

Instant Transfer 
-Recipient bank (Return to Main Menu)
-Recipient bank acc number
-Enter PIN Number (User authentication)

PIN Change
-Enter current PIN number (Return to Main Menu)
-Enter new PIN number
-Enter IC number (User authentication)

- The end of any transaction will go into loading screen and into thank you screen

**Comment by jia21001052** [comment]
"Main Menu" button

![Screenshot 2022-11-07 151724](https://user-images.githubusercontent.com/117239741/200248017-b4431a0b-1c32-4e6e-a8f7-70e650ad8e0d.png)

**Comment by NvTly** [comment]
Final checking of Functions and Details

All functions and details have been checked and confirmed to match final planned functions and details

**Comment by TalosTheGrea** [comment]
Finalized work pasted into the document link below:
https://docs.google.com/document/d/1vF-l7vk9MQk5gO98AtLDzKv303OGdPA67hYapslZVV8/edit?usp=sharing

Good job everyone, Thank you for your work!
